# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
# This will however be taken care of via grunt watch file

# Site settings
title: Corporate Programmer
email: hello@corporateprogrammer.com
description: >
  A survival guide for software developers entering the corporate world
  from small to medium businesses.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.corporateprogrammer.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /blog/:title/
exclude:
  - node_modules
  - _sass #grunt will take care of this.
